### User Create 
POST https://prod-expressjs-production.up.railway.app/api/v1/auth/register
Content-Type: application/json

{
    "first_name": "Kibow",
    "last_name": "Ewok",
    "email": "ewok@gmail.com",
    "password": "123456"
}

### User Login 
POST https://prod-expressjs-production.up.railway.app/api/v1/auth/login
Content-Type: application/json

{
    "email": "kepin@gmail.com",
    "password": "123456"
}

### Token
GET https://prod-expressjs-production.up.railway.app/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw

### Get all user
GET https://prod-expressjs-production.up.railway.app/api/v1/users

### Get all user by search
GET https://prod-expressjs-production.up.railway.app/api/v1/users?search=kes

### Get user by id
GET https://prod-expressjs-production.up.railway.app/api/v1/users/5

### Update profile
PUT https://prod-expressjs-production.up.railway.app/api/v1/users/1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw
Content-Type: application/json

{
    "address" : "Surabaya",
    "occupation" : "Backend Enginer" 
}

### Delete user
DELETE https://prod-expressjs-production.up.railway.app/api/v1/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw



#########################################
############### IMAGE ###################

### Get All Image
GET https://prod-expressjs-production.up.railway.app/api/v1/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw

### Get Image by ID
GET https://prod-expressjs-production.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw

### Edit Image
PUT https://prod-expressjs-production.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw
Content-Type: application/json

{
    "title" : "Skala Prioritas",
    "description" : "Testing upload image 1" 
}

### Delete Image by ID
DELETE https://prod-expressjs-production.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IktlcGluIiwibGFzdF9uYW1lIjoiS29jYWsiLCJlbWFpbCI6ImtlcGluQGdtYWlsLmNvbSIsImlhdCI6MTcxNDk3MzgyNX0.N_CcfHOLyH_LHmleerNg-jsrF5OCc0RqZ7Hml67bAmw